<script setup lang="ts">
import type { AppState, NavActions, Screen } from '../types/navigation'
defineProps<{state:AppState;actions:NavActions}>()
const img=(id:string,w=200,h=200)=>`https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`
const invoices=[{id:'INV-0024',date:'Sep 2024',amount:'R 250'},{id:'INV-0023',date:'Aug 2024',amount:'R 500'},{id:'INV-0022',date:'Jul 2024',amount:'R 250'}]
const settings:{title:string;rows:{label:string;icon:string;screen?:Screen;value?:string;logout?:boolean}[]}[]=[
  {title:'My account',rows:[{label:'Personal info',icon:'👤',screen:'account-personal'},{label:'My properties',icon:'⌂',screen:'account-addresses'},{label:'Payment methods',icon:'▣',screen:'account-payment'},{label:'Billing history',icon:'□',screen:'account-billing'}]},
  {title:'Plan & settings',rows:[{label:'My plan',icon:'🌿',screen:'account-plan',value:'Weekly'},{label:'Notification settings',icon:'◷',screen:'account-notifications'}]},
  {title:'More',rows:[{label:'Refer a friend',icon:'★',screen:'referral'},{label:'Help & support',icon:'?',screen:'support'},{label:'Log out',icon:'↪',logout:true}]},
]
const notifications=[{label:'Visit reminders',values:[true,false,true]},{label:'Crew on the way',values:[true,false,false]},{label:'Visit completed',values:[true,false,false]},{label:'Invoice & payment',values:[true,true,false]},{label:'Promos & offers',values:[false,false,false]}]
</script>
<template>
  <div v-if="state.screen==='account-personal'" class="px-4 pb-8 pt-4"><div class="mb-3 overflow-hidden rounded-2xl bg-white shadow-sm"><div v-for="field in [{label:'Full name',value:'Sam Mitchell'},{label:'Phone',value:'+27 82 123 4567'},{label:'Email',value:'sam@example.com'},{label:'Birthday',value:'12 March (optional)'}]" :key="field.label" class="border-b border-gray-100 px-4 py-3.5 last:border-0"><p class="text-xs font-bold text-gray-400">{{ field.label.toUpperCase() }}</p><p class="mt-0.5 text-sm">{{ field.value }}</p></div></div><button class="w-full rounded-2xl bg-[#073B24] py-3.5 text-sm font-semibold text-white">Save changes</button></div>
  <div v-else-if="state.screen==='account-addresses'" class="px-4 pb-8 pt-4"><div class="mb-3 rounded-2xl bg-white p-4 shadow-sm"><div class="mb-2 flex justify-between"><b>Home</b><button class="text-xs font-bold text-[#073B24]">Edit</button></div><p class="text-sm text-gray-600">12 Oak Street, Rondebosch, Cape Town</p><div class="mt-3 grid grid-cols-2 gap-2 text-xs text-gray-500"><span>Gate code: 1234</span><span>Dog: Buddy</span><span>Lawn: ~420m²</span><span>Gate photo on file</span></div><img :src="img('1774384735076-ac211343713c',400,160)" alt="Property" class="mt-3 h-20 w-full rounded-xl object-cover"/></div><button class="w-full rounded-2xl border-2 border-[#073B24] py-3.5 text-sm font-semibold text-[#073B24]">+ Add another property</button></div>
  <div v-else-if="state.screen==='account-payment'" class="px-4 pb-8 pt-4"><div class="mb-3 rounded-2xl bg-white p-4 shadow-sm"><div class="flex items-center gap-3 rounded-xl border-2 border-[#073B24] p-3"><span class="rounded bg-blue-600 px-2 text-[9px] font-bold text-white">VISA</span><div class="flex-1"><p class="text-sm font-semibold">•••• •••• •••• 4242</p><p class="text-xs text-gray-400">Expires 08/27</p></div><span class="rounded-full bg-[#E6F0EB] px-2 text-[10px] font-bold text-[#073B24]">Default</span></div><div class="mt-2 flex gap-2"><button class="flex-1 rounded-xl border py-2 text-xs">Change card</button><button class="flex-1 rounded-xl border py-2 text-xs">Remove</button></div></div><button class="w-full rounded-2xl border-2 border-[#073B24] py-3.5 text-sm font-semibold text-[#073B24]">+ Add new card</button></div>
  <div v-else-if="state.screen==='account-billing'" class="px-4 pb-8 pt-4"><div class="overflow-hidden rounded-2xl bg-white shadow-sm"><div v-for="invoice in invoices" :key="invoice.id" class="flex items-center gap-3 border-b border-gray-100 px-4 py-3.5 last:border-0"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-[#E6F0EB]">□</span><div class="flex-1"><p class="text-sm font-semibold">{{ invoice.id }}</p><p class="text-xs text-gray-400">{{ invoice.date }}</p></div><div class="text-right"><p class="text-sm font-bold text-[#073B24]">{{ invoice.amount }}</p><p class="text-[10px] font-bold text-[#16A34A]">Paid</p></div><button class="text-xs font-bold text-[#073B24]">PDF</button></div></div></div>
  <div v-else-if="state.screen==='account-plan'" class="px-4 pb-8 pt-4"><div class="mb-4 rounded-3xl bg-gradient-to-br from-[#073B24] to-[#0F5C3A] p-5 text-white"><span class="rounded-full bg-[#E5D403] px-2 py-0.5 text-xs font-bold text-[#073B24]">Active plan</span><h3 class="mt-2 font-[Outfit] text-xl font-bold">Weekly Maintenance</h3><p class="text-sm text-white/70">Lawn Mowing · Every week</p><div class="mt-4 flex justify-between border-t border-white/20 pt-4"><div><p class="text-xs text-white/60">Your price</p><b>R 250 / visit</b></div><div><p class="text-xs text-white/60">Next billing</p><b>1 Oct 2024</b></div></div></div><div class="flex gap-2.5"><button class="flex-1 rounded-2xl border-2 border-[#B45309] py-3 text-sm font-semibold text-[#B45309]">Pause plan</button><button class="flex-1 rounded-2xl border-2 border-[#DC2626] py-3 text-sm font-semibold text-[#DC2626]">Cancel plan</button></div></div>
  <div v-else-if="state.screen==='account-notifications'" class="px-4 pb-8 pt-4"><div class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="grid grid-cols-4 border-b px-4 py-2"><span/><span v-for="head in ['Push','SMS','WA']" :key="head" class="text-center text-xs font-bold text-gray-400">{{ head }}</span></div><div v-for="item in notifications" :key="item.label" class="grid grid-cols-4 items-center border-b px-4 py-3 last:border-0"><span class="text-xs font-medium">{{ item.label }}</span><div v-for="(on,i) in item.values" :key="i" class="flex justify-center"><div class="flex h-5 w-9 items-center rounded-full p-0.5" :class="on?'justify-end bg-[#073B24]':'justify-start bg-gray-200'"><span class="h-4 w-4 rounded-full bg-white shadow"/></div></div></div></div></div>
  <div v-else class="pb-8"><div class="flex flex-col items-center pb-5 pt-6"><img :src="img('1689728318937-17d24bc0a65c',160,160)" alt="Profile" class="mb-3 h-20 w-20 rounded-full border-[3px] border-[#E5D403] object-cover"/><p class="font-[Outfit] text-lg font-bold">Sam Mitchell</p><p class="text-xs text-gray-400">Evergro customer since March 2025</p><span class="mt-2 rounded-full bg-[#E6F0EB] px-3 py-1 text-xs font-bold text-[#073B24]">Weekly Maintenance</span></div><div v-for="section in settings" :key="section.title" class="mb-4"><p class="mb-1.5 px-4 text-xs font-bold uppercase tracking-wider text-gray-400">{{ section.title }}</p><div class="mx-4 overflow-hidden rounded-2xl bg-white shadow-sm"><button v-for="row in section.rows" :key="row.label" @click="row.logout ? actions.logout() : row.screen && actions.goTo(row.screen)" class="flex w-full items-center gap-3 border-b border-gray-100 px-4 py-3.5 text-left last:border-0"><span class="w-6 text-center">{{ row.icon }}</span><span class="flex-1 text-sm font-medium">{{ row.label }}</span><span class="text-sm text-gray-400">{{ row.value }}</span><span>›</span></button></div></div></div>
</template>
