<script setup lang="ts">
import type { NavActions, Screen } from '../types/navigation'
defineProps<{actions:NavActions}>()
const lawnImage='https://images.unsplash.com/photo-1632753214468-b4576aa0ca84?auto=format&fit=crop&w=1200&q=85'
const activity=[{color:'#16A34A',icon:'✓',title:'Lawn mowing completed',sub:'Tuesday, 17 Sep · 53 minutes',action:'View photos'},{color:'#E5D403',icon:'!',title:'Visit rescheduled by Evergro',sub:'Tuesday, 24 Sep · Weather delay',action:'View update'},{color:'#16A34A',icon:'✓',title:'Payment received',sub:'Monday, 9 Sep · Invoice INV-0024',action:'View invoice'}]
const quick:{label:string;sub:string;screen:Screen}[]=[{label:'Pay invoice',sub:'No balance due',screen:'account-billing'},{label:'Add a service',sub:'Browse treatments',screen:'services'},{label:'Refer a friend',sub:'Get R150 credit',screen:'referral'},{label:'Get help',sub:"We're here for you",screen:'support'}]
</script>
<template>
  <div class="mx-auto max-w-[1240px] p-8 xl:p-10"><div class="mb-7 flex items-end justify-between"><div><p class="mb-1 text-sm text-[#6D8179]">Thursday, 21 September</p><h1 class="font-[Outfit] text-[34px] font-bold tracking-[-0.025em] text-[#102D22]">Your lawn’s looking great, Sam.</h1></div><button @click="actions.setTab('services')" class="rounded-xl bg-[#073B24] px-5 py-3 text-sm font-semibold text-white">+ Book a service</button></div>
    <div class="grid grid-cols-12 gap-5"><section class="relative col-span-8 min-h-[274px] overflow-hidden rounded-[28px] bg-[#073B24] text-white"><img :src="lawnImage" alt="Freshly maintained green lawn" class="absolute inset-0 h-full w-full object-cover opacity-45"/><div class="absolute inset-0 bg-gradient-to-r from-[#073B24] via-[#073B24]/90 to-[#073B24]/20"/><div class="relative flex h-full flex-col p-7"><div><span class="rounded-full bg-white/14 px-3 py-1 text-[11px] uppercase">○ Upcoming visit</span><span class="ml-2 rounded-full bg-[#E5D403] px-2.5 py-1 text-[11px] font-bold text-[#073B24]">In 4 days</span></div><div class="mt-auto"><p class="font-[Outfit] text-3xl font-semibold">Thursday, 25 September</p><p class="mt-1 text-sm text-white/70">09:00–11:00 · Lawn mowing · Jake & Team</p><div class="mt-5 flex gap-2.5"><button class="rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-[#073B24]">View visit</button><button class="rounded-xl bg-white/12 px-4 py-2.5 text-xs font-semibold">Reschedule</button><button class="rounded-xl bg-white/12 px-4 py-2.5 text-xs font-semibold">Add gate note</button></div></div></div></section>
      <aside class="col-span-4 flex flex-col rounded-[28px] border border-[#E0E9E4] bg-white p-6"><p class="text-xs font-semibold uppercase text-[#84958F]">September plan</p><p class="mt-1 font-[Outfit] text-xl font-semibold">3 of 4 visits</p><div class="mt-6 grid grid-cols-4 gap-2"><div v-for="(item,i) in ['✓','✓','×','○']" :key="i" class="text-center"><div class="flex h-11 items-center justify-center rounded-xl" :class="item==='✓'?'bg-[#E8F5E9] text-[#168447]':item==='○'?'border-2 border-gray-400 text-gray-500':'bg-[#FEF2F2] text-[#DC2626]'">{{ item }}</div><p class="mt-1.5 text-[10px] text-[#84958F]">Week {{ i+1 }}</p></div></div><div class="mt-auto rounded-2xl bg-[#F7F9F8] px-4 py-3 text-xs"><span class="text-[#71837C]">Monthly total</span><b class="float-right">R 1,000</b></div></aside>
      <section class="col-span-7 rounded-[28px] border border-[#E0E9E4] bg-white p-6"><div class="mb-5 flex justify-between"><div><h2 class="font-[Outfit] text-xl font-semibold">Recent activity</h2><p class="text-xs text-[#84958F]">Updates from your lawn care team</p></div><button @click="actions.setTab('schedule')" class="text-xs font-bold text-[#0F5C3A]">View schedule →</button></div><button v-for="item in activity" :key="item.title" class="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-[#F7F9F8]"><span class="flex h-9 w-9 items-center justify-center rounded-xl text-xs font-bold" :style="{background:`${item.color}18`,color:item.color}">{{ item.icon }}</span><span class="flex-1"><b class="block text-sm">{{ item.title }}</b><span class="text-xs text-[#84958F]">{{ item.sub }}</span></span><span class="text-xs font-semibold text-[#0F5C3A]">{{ item.action }}</span></button></section>
      <section class="col-span-5 rounded-[28px] bg-[#E5D403] p-6 text-[#073B24]"><p class="text-xs font-bold uppercase">Share the good grass</p><h2 class="mt-1 font-[Outfit] text-2xl font-bold">Give R150, get R150.</h2><p class="mt-2 text-sm text-[#073B24]/70">Refer a neighbour and you’ll both save on your next lawn service.</p><button @click="actions.goTo('referral')" class="mt-5 rounded-xl bg-[#073B24] px-4 py-2.5 text-xs font-bold text-white">Invite a friend</button></section>
      <section class="col-span-12 grid grid-cols-4 gap-4"><button v-for="item in quick" :key="item.label" @click="actions.goTo(item.screen)" class="rounded-2xl border border-[#E0E9E4] bg-white p-4 text-left hover:shadow-sm"><b class="block text-sm">{{ item.label }}</b><span class="text-[11px] text-[#84958F]">{{ item.sub }}</span></button></section>
    </div>
  </div>
</template>
