<script setup lang="ts">
import { ref } from 'vue'
import type { AppState, NavActions, Screen } from '../types/navigation'
defineProps<{ state: AppState; actions: NavActions }>()
const img = (id:string,w=400,h=300) => `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`
const promoIdx=ref(0), alertDismissed=ref(false)
const promos=[{bg:'#073B24',tag:'Refer a friend',title:'Give R150, get R150',sub:'Share your code and both of you save.'},{bg:'#0F5C3A',tag:'Spring special',title:'Free fertilise with your next mow',sub:'This September only. Tap to add.'},{bg:'#2D6A4F',tag:'Popular',title:'Hedge trimming from R 200',sub:'Book before Saturday for this week.'}]
const quick:{label:string;screen:Screen}[]=[{label:'Pay invoice',screen:'account-billing'},{label:'Get help',screen:'support'},{label:'Refer a friend',screen:'referral'},{label:'Add service',screen:'services'}]
</script>
<template>
  <div class="pb-8">
    <div class="flex items-center justify-between px-4 pb-2 pt-4"><div class="flex items-center gap-3"><img :src="img('1689728318937-17d24bc0a65c',88,88)" alt="Profile" class="h-11 w-11 rounded-full border-2 border-[#E5D403] object-cover"/><div><p class="text-xs text-gray-500">Good morning</p><p class="font-[Outfit] text-[1.0625rem] font-bold text-[#073B24]">Hi, Sam</p></div></div><button @click="actions.goTo('inbox')" class="relative flex h-10 w-10 items-center justify-center rounded-full bg-white shadow">◷<span class="absolute -right-0.5 -top-0.5 flex h-4 w-4 items-center justify-center rounded-full bg-red-500 text-[9px] font-bold text-white">3</span></button></div>
    <div v-if="!alertDismissed" class="mx-4 mb-3 overflow-hidden rounded-2xl border border-[#E5D403] bg-[#FFF3CD] p-3.5"><div class="flex gap-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#E5D403]">!</span><div><p class="text-xs font-bold text-[#073B24]">Tomorrow's visit rescheduled</p><p class="mt-0.5 text-xs text-gray-600">Rain forecast for Wed morning. New time: Thu 25 Sep, 9–11 am.</p><div class="mt-2 flex gap-3"><button @click="actions.goTo('schedule')" class="text-xs font-bold text-[#073B24] underline">View</button><button @click="alertDismissed=true" class="text-xs text-gray-400">Dismiss</button></div></div></div></div>
    <div class="relative mx-4 mb-4 overflow-hidden rounded-3xl bg-gradient-to-br from-[#073B24] to-[#0F5C3A] p-4 text-white"><div class="flex justify-between"><div><span class="rounded-full bg-white/15 px-2.5 py-0.5 text-xs">Next visit</span><h3 class="mt-2 font-[Outfit] text-lg font-bold">Thu 25 Sep</h3><p class="text-sm text-white/70">9:00 – 11:00 am · Lawn Mowing</p><p class="mt-1 text-xs text-white/60">Crew: Jake & Team</p></div><img :src="img('1590820292118-e256c3ac2676',96,96)" alt="Crew" class="h-12 w-12 rounded-full border-2 border-white/30 object-cover"/></div><div class="mt-4 flex gap-2"><button v-for="item in ['Reschedule','Add gate note','Skip visit']" :key="item" class="flex-1 rounded-xl bg-white/15 py-2 text-xs font-semibold">{{ item }}</button></div></div>
    <div class="mx-4 mb-4 rounded-2xl p-4 text-white" :style="{background:promos[promoIdx].bg}"><span class="text-xs text-white/70">{{ promos[promoIdx].tag }}</span><h4 class="mt-1 font-[Outfit] font-bold">{{ promos[promoIdx].title }}</h4><p class="text-xs text-white/70">{{ promos[promoIdx].sub }}</p><div class="mt-3 flex gap-1.5"><button v-for="(_,i) in promos" :key="i" @click="promoIdx=i" class="h-1.5 rounded-full" :class="i===promoIdx ? 'w-5 bg-[#E5D403]' : 'w-1.5 bg-white/30'"/></div></div>
    <div class="mx-4 mb-4"><h3 class="mb-2 font-[Outfit] text-[1.0625rem] font-bold">Last visit</h3><button @click="actions.goTo('day-detail',{selectedDate:'2024-09-17'})" class="flex w-full overflow-hidden rounded-2xl bg-white text-left shadow-sm"><img :src="img('1526392587392-d1627b6c134a',192,192)" alt="Lawn after" class="w-24 object-cover"/><div class="p-3"><p class="text-xs font-bold text-[#16A34A]">● Completed</p><p class="mt-1 text-sm font-semibold">Tue 17 Sep</p><p class="text-xs text-gray-500">2:10 – 3:05 pm · Lawn Mowing</p></div></button></div>
    <div class="mx-4"><h3 class="mb-2 font-[Outfit] text-[1.0625rem] font-bold">Quick actions</h3><div class="grid grid-cols-2 gap-2.5"><button v-for="item in quick" :key="item.label" @click="actions.goTo(item.screen)" class="rounded-2xl bg-white p-4 text-left text-sm font-semibold text-[#073B24] shadow-sm">{{ item.label }} →</button></div></div>
  </div>
</template>
