<script setup lang="ts">
import type { NavActions } from '../types/navigation'
const props = defineProps<{ isLoggedIn: boolean; actions: NavActions }>()
const images = {
  hero: 'https://images.unsplash.com/photo-1734303023491-db8037a21f09?auto=format&fit=crop&w=1800&q=85',
  about: 'https://images.unsplash.com/photo-1689728318937-17d24bc0a65c?auto=format&fit=crop&w=1000&q=85',
  lawn: 'https://images.unsplash.com/photo-1690068023694-053da714f95f?auto=format&fit=crop&w=900&q=85',
  design: 'https://images.unsplash.com/photo-1658595060302-20219e956ad0?auto=format&fit=crop&w=900&q=85',
}
const nav = [['Services', '#services'], ['About', '#about'], ['Projects', '#projects'], ['Why Evergro', '#why-us']]
const benefits = [
  ['01', 'Reliable by design', 'Simple scheduling, clear arrival windows, and updates before every visit.'],
  ['02', 'Teams you can trust', 'Uniformed, insured professionals who respect your home and property.'],
  ['03', 'Healthier lawns', 'We care for long-term growth and colour, not just a quick cut.'],
  ['04', 'Everything in one place', 'Manage visits, payments, notes and support from your portal.'],
]
const services = [
  ['Lawn care & maintenance', 'Mowing, edging, fertilising and seasonal health plans.', images.lawn, '01'],
  ['Landscape design', 'Beautiful, functional gardens planned around your home.', images.design, '02'],
  ['Garden clean-ups', 'A complete reset for overgrown beds, hedges and outdoor areas.', images.about, '03'],
  ['Irrigation solutions', 'Efficient installations and repairs for effortless watering.', images.hero, '04'],
]
const openPortal = () => props.isLoggedIn ? props.actions.setTab('home') : props.actions.goTo('login')
</script>

<template>
  <div class="min-h-full overflow-x-hidden bg-[#FAFCFA] text-[#173228]">
    <header class="sticky top-0 z-40 border-b border-[#073B24]/8 bg-[#FAFCFA]/92 backdrop-blur-xl">
      <div class="mx-auto flex h-[76px] max-w-[1280px] items-center justify-between px-5 lg:px-8">
        <div class="flex items-center gap-2.5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-[#073B24]"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.3" stroke-linecap="round"><path d="M19 4C11 4 5.5 8.5 5.5 15.5c0 2 1 3.5 2.5 4.5 1-6 4.5-9 9-11-3.5 3-5.5 6.5-6 11 5.5-.5 9-4.5 8-16Z"/></svg></span><span class="font-[Outfit] text-[22px] font-bold tracking-[-0.04em] text-[#073B24]">evergro</span></div>
        <nav class="hidden items-center gap-7 lg:flex" aria-label="Website navigation"><a v-for="[label, href] in nav" :key="label" :href="href" class="text-sm font-semibold text-[#50665D] transition-colors hover:text-[#073B24]">{{ label }}</a></nav>
        <div class="flex items-center gap-2.5"><a href="#quote" class="hidden rounded-xl px-4 py-2.5 text-sm font-semibold text-[#073B24] sm:block">Get a quote</a><button @click="openPortal" class="flex h-11 items-center gap-2 rounded-xl bg-[#073B24] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#0F5C3A]">{{ isLoggedIn ? 'Open dashboard' : 'Customer login' }}<span>›</span></button></div>
      </div>
    </header>
    <main>
      <section class="mx-auto max-w-[1400px] px-3 pt-3 sm:px-5 lg:px-6">
        <div class="relative min-h-[680px] overflow-hidden rounded-[28px] bg-[#073B24] lg:min-h-[700px] lg:rounded-[38px]">
          <img :src="images.hero" alt="Evergro landscaping professional caring for a residential lawn" class="absolute inset-0 h-full w-full object-cover object-center"/>
          <div class="absolute inset-0 bg-gradient-to-r from-[#052D1C]/95 via-[#073B24]/75 to-[#073B24]/15"/>
          <div class="relative mx-auto flex min-h-[680px] max-w-[1240px] items-center px-6 py-20 lg:min-h-[700px] lg:px-10"><div class="max-w-[700px]">
            <span class="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3.5 py-2 text-xs font-semibold text-white backdrop-blur-md"><span class="h-2 w-2 rounded-full bg-[#E5D403]"/>Trusted lawn care across Gauteng</span>
            <h1 class="mt-7 font-[Outfit] text-[48px] font-bold leading-[0.98] tracking-[-0.045em] text-white sm:text-[62px] lg:text-[76px]">A better lawn.<br/><span class="text-[#E5D403]">Without the work.</span></h1>
            <p class="mt-6 max-w-xl text-base leading-7 text-white/72 sm:text-lg">Professional landscaping and recurring lawn care that arrives on time, keeps you informed, and leaves your outdoor space looking its best.</p>
            <div class="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#quote" class="flex h-13 items-center justify-center gap-2 rounded-2xl bg-[#E5D403] px-6 text-sm font-bold text-[#073B24] hover:bg-[#F0DF09]">Get a free estimate →</a><a href="#projects" class="flex h-13 items-center justify-center rounded-2xl border border-white/30 bg-white/10 px-6 text-sm font-semibold text-white backdrop-blur-md hover:bg-white/15">See our work</a></div>
            <div class="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-xs font-medium text-white/70"><span v-for="item in ['Insured professional teams','Easy online scheduling','Photos after every visit']" :key="item" class="flex items-center gap-2"><span class="flex h-5 w-5 items-center justify-center rounded-full bg-[#E5D403] text-[10px] font-bold text-[#073B24]">✓</span>{{ item }}</span></div>
          </div></div>
        </div>
      </section>
      <section id="quote" class="relative z-10 mx-auto -mt-10 max-w-[1120px] px-5"><div class="rounded-[26px] border border-[#DDE8E2] bg-white p-5 shadow-[0_20px_60px_rgba(7,59,36,0.13)] sm:p-7 lg:flex lg:items-center lg:gap-8"><div class="lg:w-[35%]"><p class="text-xs font-bold uppercase tracking-[0.12em] text-[#0F5C3A]">Free estimate</p><h2 class="mt-1 font-[Outfit] text-2xl font-bold tracking-[-0.02em]">What does your lawn need?</h2></div><div class="mt-5 flex flex-1 flex-col gap-3 sm:flex-row lg:mt-0"><label class="flex h-13 flex-1 items-center gap-3 rounded-xl border border-[#D4E0DA] bg-[#F8FAF9] px-4 focus-within:border-[#0F5C3A]"><span>⌖</span><input class="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#98A69F]" placeholder="Enter your street address"/></label><button class="h-13 rounded-xl bg-[#073B24] px-6 text-sm font-bold text-white hover:bg-[#0F5C3A]">Get my price</button></div></div></section>
      <section class="mx-auto max-w-[1240px] px-5 py-24 lg:px-8"><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><article v-for="[number,title,body] in benefits" :key="number" class="rounded-[24px] border border-[#E1EAE5] bg-white p-6"><span class="font-[Outfit] text-sm font-bold text-[#A0AFA8]">{{ number }}</span><h3 class="mt-10 font-[Outfit] text-xl font-semibold">{{ title }}</h3><p class="mt-2 text-sm leading-6 text-[#6D8179]">{{ body }}</p></article></div></section>
      <section id="about" class="bg-[#073B24] py-24 text-white"><div class="mx-auto grid max-w-[1240px] items-center gap-14 px-5 lg:grid-cols-2 lg:px-8"><div class="relative"><img :src="images.about" alt="Evergro team member trimming a lawn edge" class="aspect-[4/4.4] w-full rounded-[32px] object-cover"/><div class="absolute -bottom-5 -right-3 rounded-2xl bg-[#E5D403] p-5 text-[#073B24] sm:right-6"><p class="font-[Outfit] text-3xl font-bold">10+</p><p class="text-xs font-semibold">years serving Gauteng</p></div></div><div><p class="text-xs font-bold uppercase tracking-[0.14em] text-[#E5D403]">About Evergro</p><h2 class="mt-4 font-[Outfit] text-4xl font-bold leading-tight tracking-[-0.03em] sm:text-5xl">Outdoor spaces made easier to love.</h2><p class="mt-6 text-base leading-7 text-white/65">We design, build and care for gardens that fit the way you live. From reliable weekly mowing to complete landscape transformations, our team combines practical expertise with thoughtful service.</p><div class="mt-8 grid grid-cols-3 gap-4 border-t border-white/15 pt-7"><div v-for="[value,label] in [['1,200+','lawns cared for'],['4.9/5','customer rating'],['98%','on-time visits']]" :key="label"><p class="font-[Outfit] text-2xl font-bold text-[#E5D403]">{{ value }}</p><p class="mt-1 text-xs text-white/50">{{ label }}</p></div></div></div></div></section>
      <section id="services" class="mx-auto max-w-[1240px] px-5 py-24 lg:px-8"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-bold uppercase tracking-[0.14em] text-[#0F5C3A]">Our services</p><h2 class="mt-3 font-[Outfit] text-4xl font-bold tracking-[-0.03em]">Care for every kind of green.</h2></div><p class="max-w-md text-sm leading-6 text-[#6D8179]">From weekly upkeep to a complete outdoor redesign, choose the help your property needs.</p></div><div class="mt-10 grid gap-5 lg:grid-cols-2"><article v-for="[title,body,image,number] in services" :key="title" class="group relative min-h-[330px] overflow-hidden rounded-[28px]"><img :src="image" alt="" class="absolute inset-0 h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/><div class="absolute inset-0 bg-gradient-to-t from-[#052D1C]/95 via-[#073B24]/20 to-transparent"/><div class="absolute inset-x-0 bottom-0 flex items-end justify-between p-7 text-white"><div><span class="text-xs font-bold text-[#E5D403]">{{ number }}</span><h3 class="mt-2 font-[Outfit] text-2xl font-bold">{{ title }}</h3><p class="mt-1 max-w-sm text-sm text-white/65">{{ body }}</p></div><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-white text-[#073B24]">↗</span></div></article></div></section>
      <section id="projects" class="mx-5 mb-24 overflow-hidden rounded-[32px] bg-[#E7F0EB] lg:mx-auto lg:max-w-[1240px]"><div class="grid lg:grid-cols-[.8fr_1.2fr]"><div class="flex flex-col justify-center p-8 sm:p-12"><p class="text-xs font-bold uppercase tracking-[0.14em] text-[#0F5C3A]">Featured project</p><h2 class="mt-3 font-[Outfit] text-4xl font-bold tracking-[-0.03em]">A calmer garden in Rondebosch.</h2><p class="mt-4 text-sm leading-6 text-[#60766D]">A tired family lawn transformed with clean edging, healthier grass and an easy-care planting plan.</p><a href="#quote" class="mt-7 flex w-fit items-center gap-2 text-sm font-bold text-[#073B24]">Start your transformation →</a></div><img :src="images.design" alt="Landscaped residential garden project" class="h-full min-h-[420px] w-full object-cover"/></div></section>
      <section id="why-us" class="mx-auto max-w-[1000px] px-5 pb-24 text-center"><p class="text-xs font-bold uppercase tracking-[0.14em] text-[#0F5C3A]">What customers say</p><blockquote class="mt-6 font-[Outfit] text-3xl font-semibold leading-tight tracking-[-0.025em] text-[#173228] sm:text-4xl">“They arrive when they say they will, keep us updated, and the garden has never looked healthier.”</blockquote><p class="mt-5 text-sm font-semibold">Nolwazi M. <span class="font-normal text-[#84958F]">· Johannesburg</span></p></section>
      <section class="bg-[#E5D403] py-20"><div class="mx-auto flex max-w-[1100px] flex-col items-center justify-between gap-8 px-5 text-center lg:flex-row lg:text-left"><div><p class="text-xs font-bold uppercase tracking-[0.14em] text-[#073B24]/60">Ready when you are</p><h2 class="mt-2 font-[Outfit] text-4xl font-bold tracking-[-0.03em] text-[#073B24]">Let’s make your outside feel better.</h2></div><a href="#quote" class="shrink-0 rounded-2xl bg-[#073B24] px-7 py-4 text-sm font-bold text-white">Get a free estimate</a></div></section>
    </main>
    <footer class="bg-[#052D1C] py-12 text-white"><div class="mx-auto flex max-w-[1240px] flex-col gap-8 px-5 lg:px-8"><div class="flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div class="flex items-center gap-2.5"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-[#E5D403]">🌿</span><span class="font-[Outfit] text-[22px] font-bold">evergro</span></div><div class="flex flex-wrap gap-5 text-xs text-white/55"><a href="#services">Services</a><a href="#about">About</a><a href="#quote">Contact</a><button @click="openPortal">Customer portal</button></div></div><div class="flex flex-col justify-between gap-2 border-t border-white/10 pt-6 text-[11px] text-white/35 sm:flex-row"><p>© 2026 Evergro Landscapers. Part of the Evergro Group.</p><p>Privacy Policy · Terms & Conditions</p></div></div></footer>
  </div>
</template>
