<script setup lang="ts">
import type { AppState, NavActions } from '../types/navigation'
defineProps<{state?:AppState;actions:NavActions}>()
const referred=[{name:'Priya Naidoo',date:'Sep 2024',status:'Signed up',reward:'R 150'},{name:'David Chen',date:'Aug 2024',status:'Signed up',reward:'R 150'},{name:'Lerato M.',date:'Jul 2024',status:'Pending',reward:'—'}]
const progress=2/5
</script>
<template>
  <div class="px-4 pb-8 pt-4"><div class="mb-4 flex flex-col items-center rounded-3xl bg-white p-5 shadow-sm"><p class="mb-4 text-sm font-semibold text-gray-600">Your referral progress</p><div class="relative mb-4 h-36 w-36"><svg viewBox="0 0 120 120" class="h-full w-full -rotate-90"><circle cx="60" cy="60" r="52" fill="none" stroke="#E5E7EB" stroke-width="12"/><circle cx="60" cy="60" r="52" fill="none" stroke="#073B24" stroke-width="12" :stroke-dasharray="2*Math.PI*52" :stroke-dashoffset="2*Math.PI*52*(1-progress)" stroke-linecap="round"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center"><span class="font-[Outfit] text-3xl font-extrabold text-[#073B24]">2</span><span class="text-xs text-gray-400">of 5</span></div></div><p class="font-[Outfit] text-lg font-bold">3 more to unlock R 500 bonus</p><p class="mt-1 text-xs text-gray-500">Each successful referral earns you R 150</p><div class="mt-4 flex w-full justify-between border-t pt-4 text-center"><div><b class="block text-xl text-[#073B24]">R 300</b><span class="text-xs text-gray-400">Earned</span></div><div><b class="block text-xl text-[#073B24]">2</b><span class="text-xs text-gray-400">Referrals</span></div><div><b class="block text-xl text-[#073B24]">R 150</b><span class="text-xs text-gray-400">Next reward</span></div></div></div>
    <div class="mb-4 rounded-2xl bg-[#E6F0EB] p-4"><p class="mb-2 text-xs font-bold text-[#073B24]">YOUR REFERRAL CODE</p><div class="flex gap-2"><div class="flex-1 rounded-xl bg-white px-4 py-2.5 font-mono text-lg font-bold tracking-wider text-[#073B24]">SAM-EVG-47</div><button class="h-10 w-10 rounded-xl bg-[#073B24] text-white">□</button></div><p class="mt-2 text-xs text-gray-500">Share this code and your friend gets R 150 off their first visit</p></div><button class="mb-4 w-full rounded-2xl bg-[#E5D403] py-3.5 text-sm font-bold text-[#073B24]">Share your referral link</button><p class="mb-2 text-xs font-bold uppercase tracking-wider text-gray-400">People you've referred</p><div class="overflow-hidden rounded-2xl bg-white shadow-sm"><div v-for="item in referred" :key="item.name" class="flex items-center gap-3 border-b px-4 py-3.5 last:border-0"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-[#E6F0EB] text-sm font-bold text-[#073B24]">{{ item.name[0] }}</span><div class="flex-1"><p class="text-sm font-semibold">{{ item.name }}</p><p class="text-xs text-gray-400">{{ item.date }}</p></div><div class="text-right"><span class="rounded-full px-2 py-0.5 text-[10px] font-bold" :class="item.status==='Signed up'?'bg-[#E8F5E9] text-[#16A34A]':'bg-gray-100 text-gray-400'">{{ item.status }}</span><p v-if="item.reward!=='—'" class="mt-0.5 text-xs font-bold text-[#073B24]">{{ item.reward }}</p></div></div></div>
  </div>
</template>
