<script setup lang="ts">
import { computed, ref } from 'vue'
import type { AppState, NavActions } from '../types/navigation'
type Frequency='one-time'|'weekly'|'bi-weekly'|'monthly'
const props=defineProps<{state:AppState;actions:NavActions}>()
const img=(id:string,w=400,h=300)=>`https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop&auto=format`
const categories=[
  {id:1,name:'Lawn Mowing',icon:'🌿',price:'R 250',imgId:'1458245201577-fc8a130b8829',desc:'Professional mowing, edging and path blowing for a neat finish.'},
  {id:2,name:'Fertilising',icon:'🌱',price:'R 220',imgId:'1526392587392-d1627b6c134a',desc:'Tailored fertiliser treatment to boost growth, colour and root strength.'},
  {id:3,name:'Weed Control',icon:'🍃',price:'R 180',imgId:'1690068023694-053da714f95f',desc:'Targeted treatment that clears weeds without harming your lawn.'},
  {id:4,name:'Hedge Trimming',icon:'✂️',price:'R 200',imgId:'1759355787286-f1c5fd456a0d',desc:'Shape and tidy hedges, shrubs and topiary to a crisp line.'},
  {id:5,name:'Garden Clean-up',icon:'🧹',price:'R 380',imgId:'1774384735076-ac211343713c',desc:'Full tidy: raking, debris removal, bed edging and path clearing.'},
  {id:6,name:'Irrigation',icon:'💧',price:'R 650',imgId:'1526392587392-d1627b6c134a',desc:'Install, service or repair irrigation systems for effortless watering.'},
]
const questions=[{q:'Which part of the lawn needs attention?',chips:['Whole lawn','Front only','Back only','Custom area']},{q:'Any pets or kids using the lawn?',chips:['Yes','No']}]
const chatStep=ref(0),chatAnswers=ref<string[]>([]),estimate=ref(220),freq=ref<Frequency>('monthly'),code=ref('')
const service=computed(()=>categories.find(item=>item.id===(props.state.selectedServiceId||1))||categories[0])
const answer=(chip:string)=>{chatAnswers.value.push(chip);chatStep.value++;estimate.value+=Math.floor(Math.random()*60)-20}
const confirm=()=>props.actions.goTo('checkout-confirm')
</script>
<template>
  <div v-if="state.screen==='checkout-confirm'" class="flex flex-col items-center px-5 pb-8 pt-12">
    <div class="mb-4 flex h-20 w-20 items-center justify-center rounded-full bg-[#E8F5E9] text-4xl text-[#16A34A]">✓</div><h2 class="text-center font-[Outfit] text-2xl font-bold">You're all booked!</h2><p class="mt-2 text-center text-sm text-gray-500">Your first <strong>{{ service.name }}</strong> is scheduled for <strong>Thu 25 Sep</strong>, 9:00–11:00 am.</p>
    <div class="mt-6 w-full rounded-2xl bg-white p-4 shadow-sm"><p class="mb-3 text-xs font-bold text-gray-400">ADDED TO YOUR SCHEDULE</p><div class="flex items-center gap-3"><div class="flex h-12 w-12 flex-col items-center justify-center rounded-xl bg-[#073B24] text-white"><span class="text-[10px]">SEP</span><b>25</b></div><div><p class="font-semibold">Thursday, 25 September</p><p class="text-xs text-gray-500">9:00 – 11:00 am · Jake & Team</p></div></div></div>
    <button @click="actions.setTab('schedule')" class="mt-4 w-full rounded-2xl bg-[#073B24] py-3.5 text-sm font-semibold text-white">View in Schedule</button><button @click="actions.setTab('home')" class="mt-3 text-sm font-medium text-[#073B24]">Back to Home</button>
  </div>
  <div v-else-if="state.screen==='checkout'" class="pb-28">
    <div class="px-4 pt-4"><div class="mb-3 rounded-2xl bg-white p-4 shadow-sm"><p class="mb-2 text-xs font-bold text-gray-400">ORDER SUMMARY</p><div class="flex justify-between text-sm"><span>{{ service.name }}</span><b>{{ service.price }}</b></div><div class="mt-1 flex justify-between text-sm text-gray-500"><span>Frequency</span><span class="capitalize">{{ freq }}</span></div><div class="mt-1 flex justify-between text-sm text-gray-500"><span>Address</span><span>12 Oak Street</span></div><div class="mt-3 flex justify-between border-t pt-3"><b>Total</b><b class="text-[#073B24]">{{ service.price }}</b></div></div>
      <div class="mb-3 rounded-2xl bg-white p-4 shadow-sm"><p class="mb-2 text-xs font-bold text-gray-400">PAYMENT METHOD</p><div class="flex items-center gap-3 rounded-xl border-2 border-[#073B24] p-3"><span class="rounded bg-blue-600 px-2 text-[9px] font-bold text-white">VISA</span><span class="text-sm">•••• 4242</span><span class="ml-auto text-xs font-bold text-[#073B24]">Default</span></div></div>
      <div class="rounded-2xl bg-white p-4 shadow-sm"><p class="mb-2 text-xs font-bold text-gray-400">PROMO OR REFERRAL CODE</p><div class="flex gap-2"><input :value="code" @input="code=($event.target as HTMLInputElement).value.toUpperCase()" placeholder="e.g. FRIEND150" class="min-w-0 flex-1 rounded-xl border-2 border-gray-200 px-3 py-2.5 text-sm"/><button class="rounded-xl bg-[#073B24] px-4 text-sm font-bold text-white">Apply</button></div></div>
    </div><div class="fixed inset-x-0 bottom-16 mx-auto max-w-sm border-t bg-white px-4 pb-3 pt-3"><button @click="confirm" class="w-full rounded-2xl bg-[#073B24] py-4 font-bold text-white">Confirm and pay {{ service.price }}</button></div>
  </div>
  <div v-else-if="state.screen==='service-chat'" class="pb-8"><div class="px-4 pb-3 pt-4"><p class="mb-4 text-xs text-gray-400">Evergro Assistant is calculating your price…</p><div class="flex flex-col gap-3"><div v-for="(item,i) in chatAnswers" :key="i" class="flex flex-col gap-2"><div class="max-w-[80%] self-start rounded-2xl rounded-tl-sm bg-[#E6F0EB] px-4 py-2.5 text-sm font-medium text-[#073B24]">{{ questions[i]?.q }}</div><div class="self-end rounded-2xl rounded-tr-sm bg-[#073B24] px-4 py-2.5 text-sm text-white">{{ item }}</div></div><div v-if="chatStep<questions.length" class="max-w-[80%] self-start rounded-2xl rounded-tl-sm bg-[#E6F0EB] px-4 py-2.5 text-sm font-medium text-[#073B24]">{{ questions[chatStep].q }}</div></div>
    <div v-if="chatStep<questions.length" class="mt-4 flex flex-wrap gap-2"><button v-for="chip in questions[chatStep].chips" :key="chip" @click="answer(chip)" class="rounded-full border-2 border-[#073B24] px-4 py-2 text-sm font-semibold text-[#073B24]">{{ chip }}</button></div>
    <div v-if="chatStep>0" class="mt-4 rounded-2xl bg-[#073B24] p-4"><p class="text-xs text-white/70">Live estimate</p><p class="font-[Outfit] text-2xl font-bold text-[#E5D403]">R {{ estimate }}</p><p class="text-xs text-white/60">Based on your answers</p></div>
    <div v-if="chatStep>=questions.length" class="mt-4 flex flex-col gap-2.5"><button @click="actions.goTo('checkout',{selectedServiceId:service.id})" class="w-full rounded-2xl bg-[#073B24] py-3.5 text-sm font-bold text-white">Accept R {{ estimate }} and pay</button><button class="w-full rounded-2xl border-2 border-[#073B24] py-3.5 text-sm font-semibold text-[#073B24]">Send to Evergro for a firm quote</button></div></div></div>
  <div v-else-if="state.screen==='service-detail'" class="pb-28">
    <div class="relative h-[200px]"><img :src="img(service.imgId,400,400)" :alt="service.name" class="h-full w-full object-cover"/><div class="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"/><span class="absolute bottom-4 left-4 text-3xl">{{ service.icon }}</span></div>
    <div class="px-4 pt-4"><h2 class="font-[Outfit] text-[1.375rem] font-bold">{{ service.name }}</h2><p class="mt-1.5 text-sm leading-relaxed text-gray-500">{{ service.desc }}</p><div class="mt-4 rounded-2xl bg-[#E6F0EB] p-4"><span class="font-[Outfit] text-[1.75rem] font-extrabold text-[#073B24]">{{ service.price }}</span><span class="ml-2 text-sm text-gray-500">per visit</span><details class="mt-2"><summary class="cursor-pointer text-xs font-medium text-[#073B24]">How we calculated this</summary><p class="mt-2 text-xs text-gray-600">Lawn size (420m²) · Frequency bonus included</p></details></div>
      <p class="mb-2 mt-4 text-sm font-bold">How often?</p><div class="grid grid-cols-2 gap-2"><button v-for="item in ['one-time','weekly','bi-weekly','monthly']" :key="item" @click="freq=item as Frequency" class="rounded-xl border-2 py-2.5 text-sm font-semibold capitalize" :class="freq===item ? 'border-[#073B24] bg-[#073B24] text-white':'border-gray-200 bg-white text-gray-700'">{{ item }}</button></div>
      <p class="mb-2 mt-4 text-sm font-bold">Preferred start date</p><button class="w-full rounded-2xl border-2 border-gray-200 px-4 py-3.5 text-left text-sm text-gray-500">Choose a date…</button><p class="mb-2 mt-4 text-sm font-bold">Notes for the crew</p><textarea rows="3" placeholder="e.g. Dog is in the backyard — please keep gate closed" class="w-full resize-none rounded-2xl border-2 border-gray-200 px-4 py-3 text-sm"/>
      <button @click="actions.goTo('service-chat',{selectedServiceId:service.id})" class="mt-3 w-full rounded-2xl border-2 border-[#073B24] py-3 text-sm font-semibold text-[#073B24]">Get a personalised quote</button>
    </div><div class="fixed inset-x-0 bottom-16 mx-auto max-w-sm border-t bg-white px-4 pb-3 pt-3"><div class="flex gap-2.5"><button class="flex-1 rounded-2xl border-2 border-[#073B24] py-3.5 text-sm font-semibold text-[#073B24]">Add to plan</button><button @click="actions.goTo('checkout',{selectedServiceId:service.id})" class="flex-1 rounded-2xl bg-[#073B24] py-3.5 text-sm font-bold text-white">Purchase now</button></div></div>
  </div>
  <div v-else class="pb-8"><div class="px-4 pt-4"><p class="mb-4 text-sm text-gray-500">Professional lawn care, calculated for your property</p><div class="mb-6 grid grid-cols-2 gap-3"><button v-for="item in categories" :key="item.id" @click="actions.goTo('service-detail',{selectedServiceId:item.id})" class="overflow-hidden rounded-2xl bg-white text-left shadow-sm transition-transform active:scale-95"><img :src="img(item.imgId,300,180)" :alt="item.name" class="h-[90px] w-full object-cover"/><div class="p-3"><p class="text-sm font-semibold">{{ item.icon }} {{ item.name }}</p><p class="text-xs font-bold text-[#073B24]">from {{ item.price }}</p></div></button></div><h3 class="mb-3 font-[Outfit] text-[1.0625rem] font-bold">Popular for your home</h3><button v-for="item in categories.slice(0,3)" :key="item.id" @click="actions.goTo('service-detail',{selectedServiceId:item.id})" class="mb-3 flex w-full items-center gap-3 rounded-2xl bg-white p-3 text-left shadow-sm"><img :src="img(item.imgId,128,128)" :alt="item.name" class="h-16 w-16 rounded-xl object-cover"/><div><p class="text-sm font-semibold">{{ item.name }}</p><p class="text-xs text-gray-500">{{ item.desc.slice(0,50) }}…</p><p class="mt-1 text-sm font-bold text-[#073B24]">Your price: {{ item.price }}</p></div></button></div></div>
</template>
