<script setup lang="ts">
import { computed, ref } from 'vue'
import type { AppState, NavActions } from '../types/navigation'
const props=defineProps<{state:AppState;actions:NavActions}>()
const faqs=[{q:'What happens if you skip my visit?',a:"If we need to skip your visit due to weather or crew issues, we'll notify you and roll your visit to the next available slot. No extra charge applies."},{q:'How do I change my mowing day?',a:'Go to Schedule, tap any upcoming visit, then Reschedule.'},{q:'Why was I charged twice?',a:'This can happen if you added a one-off service alongside your regular plan. Open Billing History to check.'},{q:'Can I pause my plan for holidays?',a:'Yes. Open My Plan, then Pause plan.'},{q:'How do I update my gate code?',a:'Go to Account, My Properties, then Edit.'}]
const search=ref(''),openFaq=ref<number|null>(null),cat=ref('Service issue'),desc=ref('')
const filtered=computed(()=>faqs.filter(item=>!search.value||item.q.toLowerCase().includes(search.value.toLowerCase())))
const messages=[{from:'you',text:'I was charged twice in August',time:'2w ago'},{from:'evergro',text:'Hi Sam, we can see the duplicate and have issued a refund. It should appear in 3–5 days.',time:'2w ago'},{from:'you',text:'Thanks, refund received!',time:'13d ago'}]
</script>
<template>
  <div v-if="state.screen==='ticket-detail'" class="flex h-full flex-col pb-4"><div class="mx-4 mb-3 mt-4 rounded-2xl bg-white p-3 shadow-sm"><div class="flex justify-between"><b class="text-sm">#001 · Billing</b><span class="rounded-full bg-[#E8F5E9] px-2 text-xs font-bold text-[#16A34A]">Resolved</span></div></div><div class="flex-1 space-y-3 overflow-y-auto px-4"><div v-for="(message,i) in messages" :key="i" class="flex" :class="message.from==='you'?'justify-end':'justify-start'"><div class="max-w-[80%] rounded-2xl px-4 py-2.5" :class="message.from==='you'?'rounded-tr-sm bg-[#073B24] text-white':'rounded-tl-sm bg-[#E6F0EB]'"><p v-if="message.from==='evergro'" class="mb-1 text-[10px] font-bold text-[#073B24]">Evergro Support</p><p class="text-sm">{{ message.text }}</p><p class="mt-1 text-[10px] opacity-60">{{ message.time }}</p></div></div></div><div class="mt-2 flex gap-2 px-4 pt-3"><button class="flex-1 rounded-xl border-2 border-[#16A34A] py-2.5 text-sm font-semibold text-[#16A34A]">Mark resolved</button><button class="flex-1 rounded-xl border-2 border-gray-200 py-2.5 text-sm font-semibold text-gray-500">Reopen</button></div></div>
  <div v-else-if="state.screen==='ticket-form'" class="px-4 pb-8 pt-4"><p class="mb-2 text-sm font-bold">Category</p><div class="mb-4 flex flex-wrap gap-2"><button v-for="item in ['Service issue','Billing','Schedule change','Other']" :key="item" @click="cat=item" class="rounded-full border-2 px-3 py-1.5 text-sm font-semibold" :class="cat===item?'border-[#073B24] bg-[#073B24] text-white':'border-gray-200'">{{ item }}</button></div><p class="mb-2 text-sm font-bold">Linked visit (optional)</p><button class="mb-4 w-full rounded-2xl border-2 border-gray-200 px-4 py-3 text-left text-sm text-gray-400">Select a visit date…</button><p class="mb-2 text-sm font-bold">Description</p><textarea v-model="desc" rows="4" placeholder="Tell us what happened…" class="mb-3 w-full resize-none rounded-2xl border-2 border-gray-200 px-4 py-3 text-sm"/><button class="mb-4 w-full rounded-2xl border-2 border-dashed border-gray-300 py-3 text-sm text-gray-400">Add a photo</button><button @click="actions.goTo('ticket-detail')" class="w-full rounded-2xl bg-[#073B24] py-4 font-bold text-white">Submit ticket</button></div>
  <div v-else class="px-4 pb-8 pt-4"><input v-model="search" placeholder="Search FAQs…" class="mb-4 w-full rounded-2xl border-2 border-gray-100 bg-white px-4 py-3 text-sm outline-none focus:border-[#073B24]"/><div class="mb-5 grid grid-cols-3 gap-2.5"><button v-for="item in ['Live chat','WhatsApp','Call us']" :key="item" class="rounded-2xl bg-white py-3.5 text-xs font-semibold shadow-sm">{{ item }}</button></div><button @click="actions.goTo('ticket-form')" class="mb-4 flex w-full items-center gap-3 rounded-2xl bg-white p-4 text-left shadow-sm"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-[#E6F0EB]">?</span><span class="flex-1"><b class="block text-sm">Create a support ticket</b><span class="text-xs text-gray-400">We'll reply within a few hours</span></span><span>›</span></button><p class="mb-2 text-xs font-bold uppercase tracking-wider text-gray-400">My tickets</p><button @click="actions.goTo('ticket-detail')" class="mb-3 flex w-full items-center gap-3 rounded-2xl bg-white p-4 text-left shadow-sm"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-[#E8F5E9] text-[#16A34A]">✓</span><span class="flex-1"><b class="text-sm">#001</b><span class="ml-2 rounded-full bg-[#E8F5E9] px-2 text-[10px] font-bold text-[#16A34A]">Resolved</span><span class="mt-1 block text-xs text-gray-500">Billing · Updated 2w ago</span></span></button><p class="mb-2 text-xs font-bold uppercase tracking-wider text-gray-400">FAQs</p><div class="overflow-hidden rounded-2xl bg-white shadow-sm"><div v-for="(faq,i) in filtered" :key="faq.q" class="border-b last:border-0"><button @click="openFaq=openFaq===i?null:i" class="flex w-full px-4 py-3.5 text-left"><p class="flex-1 text-sm font-medium">{{ faq.q }}</p><span>⌄</span></button><p v-if="openFaq===i" class="px-4 pb-4 text-sm leading-relaxed text-gray-500">{{ faq.a }}</p></div><p v-if="!filtered.length" class="p-6 text-center text-sm text-gray-400">No results for "{{ search }}"</p></div></div>
</template>
